language: ruby
rvm:
  - 1.9.3
env:
  - "RAILS_VERSION=3.2.0"
script: bundle exec rspec spec
before_script:
  - psql -c "CREATE USER cti WITH ENCRYPTED PASSWORD 'cti';" -U postgres
  - psql -c "CREATE DATABASE dbview_cti_test WITH OWNER cti;" -U postgres
  - ruby ./migrate_up.rb
after_success_script:
  - ruby ./migrate_down.rb
