language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - jruby-19mode
  - rbx-2
env:
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=4.1.0"
  - "RAILS_VERSION=4.2.0"
script: bundle exec rspec spec/models
before_script:
  - psql -c "CREATE USER cti WITH ENCRYPTED PASSWORD 'cti';" -U postgres
  - psql -c "CREATE DATABASE dbview_cti_test WITH OWNER cti;" -U postgres
  - ruby ./migrate_up.rb
after_success_script:
  - ruby ./migrate_down.rb
before_install:
  - gem install bundler
